# Generated by Django 2.2.10 on 2021-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0180_auto_20211114_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilier',
            name='facture',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', null=True, upload_to='invent_files'),
        ),
    ]
