# Generated by Django 2.2.10 on 2021-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0181_auto_20211115_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilier',
            name='facture',
            field=models.FileField(null=True, upload_to='invent_files'),
        ),
    ]
