# Generated by Django 2.2.10 on 2021-11-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0182_auto_20211115_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilier',
            name='valeur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
