# Generated by Django 2.2.10 on 2021-11-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0184_auto_20211117_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_avance', models.CharField(max_length=12)),
                ('encours', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_budg', models.CharField(max_length=4, unique=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='credit',
            name='chapitre-article',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='chapitre',
        ),
        migrations.AddField(
            model_name='immobilier',
            name='observation',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='avance',
            name='chapitres',
            field=models.ManyToManyField(to='scolar.Chapitre'),
        ),
        migrations.AddField(
            model_name='avance',
            name='exercice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scolar.Exercice'),
        ),
        migrations.AddField(
            model_name='credit',
            name='avance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scolar.Avance'),
        ),
    ]
