# Generated by Django 2.2.10 on 2021-11-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0185_auto_20211121_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='encours',
            field=models.BooleanField(blank=True, default='True'),
        ),
    ]
