# Generated by Django 2.2.10 on 2021-11-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0187_auto_20211121_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='chapitre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scolar.Chapitre'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(fields=('chapitre', 'article'), name='chapitre-article'),
        ),
    ]
