# Generated by Django 2.2.10 on 2021-11-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0188_auto_20211124_1051'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credit',
            name='chapitre-article',
        ),
    ]
