# Generated by Django 2.2.10 on 2022-02-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0189_auto_20211124_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereau',
            name='date_borderau',
            field=models.DateField(blank=True, null=True),
        ),
    ]
