# Generated by Django 2.2.10 on 2022-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0192_immobilier_bureau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bureau',
            name='bloc',
        ),
        migrations.AddField(
            model_name='bloc',
            name='bureaux',
            field=models.ManyToManyField(to='scolar.Bureau'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='famille',
            field=models.CharField(choices=[('01', 'Logiciels et Applicatifs'), ('02', 'Materiel informatique'), ('03', 'Materiel et Mobilier de bureau et denseingement '), ('04', 'Materiel de securite'), ('05', 'Climatisation'), ('07', 'Equipement menager'), ('08', 'Materiel automobile'), ('09', 'Materiel supervision systeme'), ('10', 'Autres'), ('11', 'Logiciels de securite'), ('12', 'Materiel archivage'), ('13', 'Materiel detection intrusion'), ('14', 'Logiciels detection intrusion'), ('15', 'Materiel Reseau VSAT'), ('16', 'Logiciel Archivage Test'), ('17', 'Logiciels archivage'), ('18', 'Materiel messagerie'), ('19', 'Logiciels messagerie'), ('20', 'Materiel archivage Backup'), ('21', 'Materiel archivage Test'), ('22', 'Logiciel Archivage Backup'), ('23', 'Materiel de sport'), ('24', 'Audio visuelle '), ('25', 'Materiel medical ')], max_length=2),
        ),
    ]
