# Generated by Django 2.2.10 on 2022-02-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0194_auto_20220228_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='bloc',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='scolar.Bloc'),
        ),
    ]
