# Generated by Django 2.2.10 on 2022-02-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0195_auto_20220228_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobilier',
            name='bloc',
        ),
    ]
