# Generated by Django 2.2.10 on 2022-02-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0196_remove_immobilier_bloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilier',
            name='bureau',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Bureau'),
        ),
    ]
