# Generated by Django 2.2.10 on 2022-03-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0197_auto_20220228_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilier',
            name='bureau',
            field=models.ForeignKey(blank=True, default='01', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Bureau'),
        ),
    ]
