# Generated by Django 2.2.10 on 2022-04-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0199_auto_20220412_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereau',
            name='etat_borderau',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
