# Generated by Django 2.2.10 on 2022-04-14 13:18

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0201_auto_20220414_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='credit_non_allouee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='avance',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=9),
        ),
    ]
