# Generated by Django 2.2.10 on 2022-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0203_auto_20221002_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banque',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='banque',
            name='nom_a',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
