# Generated by Django 2.2.10 on 2022-10-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0203_auto_20221016_1415'),
        ('scolar', '0204_auto_20221002_0924'),
    ]

    operations = [
    ]
