# Generated by Django 2.2.10 on 2022-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0207_auto_20221005_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angagement_S2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('nature', models.CharField(max_length=150)),
            ],
        ),
    ]
