# Generated by Django 2.2.10 on 2022-10-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0208_angagement_s2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Angagement_S2',
            new_name='Engagement_S2',
        ),
    ]
