# Generated by Django 2.2.10 on 2022-10-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0209_auto_20221006_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_s2',
            name='epc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
