# Generated by Django 2.2.10 on 2022-10-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0203_auto_20221016_1415'),
        ('scolar', '0209_auto_20221006_1105'),
    ]

    operations = [
    ]
