# Generated by Django 3.2 on 2022-11-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0209_auto_20221006_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fournisseur', models.CharField(max_length=10, null=True)),
                ('nom_fournisseur', models.CharField(max_length=200, null=True)),
                ('adresse_fournisseur', models.CharField(max_length=200, null=True)),
                ('num_cmpt_fournisseur', models.IntegerField(null=True)),
                ('cle_cmpt_fournisseur', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='credit_s2',
            name='epc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.RenameModel(
            old_name='Engagement_S2',
            new_name='Type_Engagement_S2',
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('observation', models.CharField(default='', max_length=300)),
                ('annee_budg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annee_budg', to='scolar.anneeuniv')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='scolar.article')),
                ('chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapitre', to='scolar.chapitre')),
                ('credit_alloue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_alloue', to='scolar.credit_s2')),
                ('type_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_engagement', to='scolar.type_engagement_s2')),
            ],
        ),
    ]
