# Generated by Django 2.2.10 on 2022-10-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0205_merge_20221017_0958'),
        ('scolar', '0209_auto_20221006_1105'),
    ]

    operations = [
    ]
