# Generated by Django 2.2.10 on 2022-10-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0210_merge_20221018_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit_S2',
        ),
    ]
