# Generated by Django 2.2.10 on 2022-10-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0211_auto_20221018_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_s2',
            name='article',
        ),
        migrations.RemoveField(
            model_name='credit_s2',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='credit_s2',
            name='exercice',
        ),
        migrations.DeleteModel(
            name='Engagement_S2',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='credit_non_allouee',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='credit_non_allouee_currency',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='total_currency',
        ),
        migrations.DeleteModel(
            name='Credit_S2',
        ),
    ]
