# Generated by Django 2.2.10 on 2022-10-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0211_fournisseur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engagement_S2',
            new_name='Type_Engagement_S2',
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('observation', models.CharField(default='', max_length=300)),
                ('annee_budg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annee_budg', to='scolar.AnneeUniv')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='scolar.Article')),
                ('chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapitre', to='scolar.Chapitre')),
                ('type_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_engagement', to='scolar.Type_Engagement_S2')),
            ],
        ),
    ]
