# Generated by Django 2.2.10 on 2022-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0212_auto_20221018_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fournisseur', models.CharField(max_length=10, null=True)),
                ('nom_fournisseur', models.CharField(max_length=200, null=True)),
                ('adresse_fournisseur', models.CharField(max_length=200, null=True)),
                ('num_cmpt_fournisseur', models.IntegerField(null=True)),
                ('cle_cmpt_fournisseur', models.IntegerField(null=True)),
            ],
        ),
    ]
