# Generated by Django 2.2.10 on 2022-10-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0213_auto_20221023_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eng',
            new_name='Engagement',
        ),
    ]
