# Generated by Django 2.2.10 on 2022-10-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0213_engagement_credit_s2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='annee_budg',
        ),
    ]
