# Generated by Django 2.2.10 on 2022-10-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0214_credit_s2_engagement_type_engagement_s2'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_s2',
            name='epc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='credit_alloue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_alloue', to='scolar.Credit_S2'),
        ),
    ]
