# Generated by Django 2.2.10 on 2022-10-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0214_auto_20221023_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='annee_univ',
        ),
        migrations.AddField(
            model_name='engagement',
            name='annee_budg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annee_budg', to='scolar.AnneeUniv'),
        ),
    ]
