# Generated by Django 2.2.10 on 2022-10-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0215_auto_20221024_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_s2',
            name='epc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
