# Generated by Django 2.2.10 on 2022-11-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0215_auto_20221026_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='article',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='chapitre',
        ),
        migrations.AddField(
            model_name='article',
            name='posteriori',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AlterField(
            model_name='credit_s2',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_credit', to='scolar.Article'),
        ),
    ]
