# Generated by Django 2.2.10 on 2022-10-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0217_engagement_credit_alloue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='credit_alloue',
        ),
    ]
