# Generated by Django 2.2.10 on 2022-10-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0219_engagement_credit_alloue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='credit_alloue',
        ),
        migrations.AddField(
            model_name='credit_s2',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement', to='scolar.Engagement'),
        ),
        migrations.AlterField(
            model_name='credit_s2',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_credit', to='scolar.Article'),
        ),
    ]
