# Generated by Django 2.2.10 on 2022-10-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0220_auto_20221027_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_s2',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_s2', to='scolar.Engagement'),
        ),
    ]
