# Generated by Django 2.2.10 on 2022-10-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0221_auto_20221027_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_s2',
            name='engagement',
        ),
        migrations.AddField(
            model_name='engagement',
            name='credit_alloue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_alloue', to='scolar.Credit_S2'),
        ),
    ]
