# Generated by Django 2.2.10 on 2022-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0222_auto_20221027_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='article',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='chapitre',
        ),
        migrations.AddField(
            model_name='article',
            name='posteriori',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
