# Generated by Django 2.2.10 on 2022-11-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0223_auto_20221106_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posteriori',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
