# Generated by Django 2.2.10 on 2022-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0225_auto_20221107_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posteriori',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
