# Generated by Django 2.2.10 on 2022-11-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0228_engagement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='type',
        ),
    ]
