# Generated by Django 2.2.10 on 2022-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0231_remove_engagement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='type',
            field=models.CharField(choices=[('01', 'Prise en charge'), ('02', 'Depence')], max_length=2, null=True),
        ),
    ]
