# Generated by Django 2.2.10 on 2022-11-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0232_engagement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='type',
            field=models.CharField(choices=[('01', 'Prise en charge'), ('02', 'Depence')], default='', max_length=2, null=True),
        ),
    ]
