# Generated by Django 2.2.10 on 2022-11-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0233_auto_20221116_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='type_engagement',
        ),
    ]
