# Generated by Django 2.2.10 on 2022-11-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0234_remove_engagement_type_engagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mandat', models.IntegerField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('article_mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_mandat', to='scolar.Article')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement', to='scolar.Engagement')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaire', to='scolar.Fournisseur')),
            ],
        ),
    ]
