# Generated by Django 2.2.10 on 2022-11-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0235_auto_20221127_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_mandat', to='scolar.Article'),
        ),
    ]
