# Generated by Django 2.2.10 on 2022-11-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0236_remove_mandat_article_mandat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='article_mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_mandat', to='scolar.Article'),
        ),
    ]
