# Generated by Django 2.2.10 on 2022-12-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0238_mandat_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='annee_budge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annee_budge', to='scolar.AnneeUniv'),
        ),
        migrations.AddField(
            model_name='mandat',
            name='credit_s2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_s2', to='scolar.Credit_S2'),
        ),
    ]
