# Generated by Django 2.2.10 on 2022-12-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0239_auto_20221207_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandat',
            name='article',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='engagement',
        ),
        migrations.AlterField(
            model_name='mandat',
            name='credit_s2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_s2_mandat', to='scolar.Credit_S2'),
        ),
    ]
