# Generated by Django 2.2.10 on 2023-05-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0240_transfert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_fact', models.IntegerField(null=True)),
                ('date_fact', models.DateField(blank=True, null=True)),
                ('type_facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Type_Facture', to='scolar.Type_Facture')),
            ],
        ),
    ]
