# Generated by Django 2.2.10 on 2023-01-29 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0241_auto_20221219_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandat_engagement', to='scolar.Mandat'),
        ),
    ]
