# Generated by Django 2.2.10 on 2023-05-30 10:09

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0241_facture_type_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='credit_non_allouee',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
