# Generated by Django 2.2.10 on 2023-02-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0243_auto_20230205_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_s2',
            name='mandat',
        ),
        migrations.AddField(
            model_name='engagement',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandat_engagement', to='scolar.Mandat'),
        ),
    ]
