# Generated by Django 2.2.10 on 2023-03-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0244_auto_20230205_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banque', to='scolar.Banque'),
        ),
    ]
