# Generated by Django 2.2.10 on 2023-03-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0245_fournisseur_banque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_fact', models.IntegerField(null=True)),
                ('date_fact', models.DateField(blank=True, null=True)),
                ('type_fact', models.CharField(choices=[('Bon de commande', 'Bon de commande'), ('Facture proformat', 'Facture proformat'), ('Facture definitive', 'Facture definitive'), ('Titre de perception', 'Titre de perception'), ('Contrat', 'Contrat'), ('Police assurance', 'Police assurance')], default='', max_length=15, null=True)),
            ],
        ),
    ]
