# Generated by Django 2.2.10 on 2023-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0247_auto_20230319_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_fact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
