# Generated by Django 2.2.10 on 2023-03-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0248_auto_20230320_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='facture',
            name='type_fact',
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Type_Facture', to='scolar.Type_Facture'),
        ),
    ]
