# Generated by Django 2.2.10 on 2023-03-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0250_mandat_type_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='num',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
