# Generated by Django 2.2.10 on 2023-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0251_auto_20230329_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
