# Generated by Django 2.2.10 on 2023-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0252_auto_20230416_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='type',
            field=models.CharField(choices=[('Prise en charge', 'Prise en charge'), ('Depence', 'Depence'), ('Fiche de regularisation de la provision', 'Fiche de regularisation de la provision')], default='', max_length=60, null=True),
        ),
    ]
