# Generated by Django 2.2.10 on 2023-05-29 13:51

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0255_auto_20230529_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='encours',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='credit_non_allouee',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
