# Generated by Django 2.2.10 on 2023-05-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0256_auto_20230529_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='encours',
        ),
        migrations.AddField(
            model_name='exercice',
            name='exe_encours',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
