# Generated by Django 2.2.10 on 2023-06-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0257_auto_20230531_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='mandat',
        ),
    ]
