# Generated by Django 2.2.10 on 2023-06-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0260_engagement_mandat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='mandat',
        ),
    ]
