# Generated by Django 2.2.10 on 2023-06-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0261_remove_engagement_mandat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='facture_mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_mandat', to='scolar.Facture'),
        ),
    ]
