# Generated by Django 2.2.10 on 2023-06-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0262_mandat_facture_mandat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='num_fact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
